In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/train_data.csv")
df.head()

C:\Users\fam-01\AppData\Local\Temp\ipykernel_11528\2032046944.py:1: DtypeWarning: Columns (0: vote) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/train_data.csv")

,overall,vote,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,2,NaN,False,2016-11-11,A2OSUEZJIN7BI,0511189877,NaN,Chris,I have an older URC-WR7 remote and thought thi...,Cannot Learn,1478822400
1,5,NaN,True,2016-06-06,A2NETQRG6JHIG7,0511189877,NaN,Qrysta White,First time I've EVER had a remote that needed ...,zero programming needed! Miracle!?,1465171200
2,4,NaN,True,2016-03-10,A12JHGROAX49G7,0511189877,NaN,Linwood,Got them and only 2 of them worked. company ca...,Works Good and programs easy.,1457568000
3,5,NaN,True,2016-01-14,A1KV65E2TMMG6F,0511189877,NaN,Dane Williams,I got tired of the remote being on the wrong s...,Same as TWC remote,1452729600
4,5,NaN,True,2016-10-20,A280POPEWI0NSA,0594459451,NaN,Kristina H.,After purchasing cheap cords from another webs...,Good Quality Cord,1476921600

In [3]:
brand_df = pd.read_csv("data/title_brand.csv")
brand_df.head()

,asin,title,brand
0,0011300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,GeoVision
1,0043396828,"Books ""Handbook of Astronomical Image Processi...",33 Books Co.
2,0060009810,One Hot Summer,Visit Amazon's Carolina Garcia Aguilera Page
3,0060219602,Hurray for Hattie Rabbit: Story and pictures (...,Visit Amazon's Dick Gackenbach Page
4,0060786817,sex.lies.murder.fame.: A Novel,Visit Amazon's Lolita Files Page

In [6]:
five_star_reviews = df[df["overall"] == 5]

In [7]:
top_products = (
    five_star_reviews.groupby("asin").size().reset_index(name="five_star_count")
)

In [9]:
top_products = top_products.merge(brand_df, on="asin", how="left")

In [10]:
top_products = top_products.sort_values(by="five_star_count", ascending=False)

In [11]:
top10 = top_products.head(10)

In [12]:
result = top10[["brand", "title", "five_star_count"]]

print(result)

                        brand  \
51280    Cambridge Soundworks
34849                 NETGEAR
67076                    Roku
6373                 StarTech
11428                Logitech
39413                 Samsung
43298                    Asus
6497                VideoSecu
40417  Arlo Technologies, Inc
39378                 Samsung

                                                   title  five_star_count
51280  OontZ Angle 3 Enhanced Stereo Edition IPX5 Spl...             1163
34849          NETGEAR N300 WiFi Range Extender (EX2700)              659
67076  Roku Streaming Stick (3600R) - HD Streaming Pl...              600
6373   StarTech USB 2.0 to SATA IDE Adapter (USB2SATA...              598
11428  Logitech M570 Wireless Trackball Mouse &ndash;...              552
39413  Samsung 850 EVO 500GB 2.5-Inch SATA III Intern...              529
43298  ASUS Tri-Band Gigabit (AC3200) WiFi Router (Up...              471
6497   VideoSecu ML531BE TV Wall Mount for Most 27&qu...              448
40417  Arlo - Wireless Home Security Camera System | ...              433
39378  Samsung 850 EVO 250GB 2.5-Inch SATA III Intern...              431

In [13]:
result.reset_index(drop=True, inplace=True)
result.index += 1
result

,brand,title,five_star_count
1,Cambridge Soundworks,OontZ Angle 3 Enhanced Stereo Edition IPX5 Spl...,1163
2,NETGEAR,NETGEAR N300 WiFi Range Extender (EX2700),659
3,Roku,Roku Streaming Stick (3600R) - HD Streaming Pl...,600
4,StarTech,StarTech USB 2.0 to SATA IDE Adapter (USB2SATA...,598
5,Logitech,Logitech M570 Wireless Trackball Mouse &ndash;...,552
6,Samsung,Samsung 850 EVO 500GB 2.5-Inch SATA III Intern...,529
7,Asus,ASUS Tri-Band Gigabit (AC3200) WiFi Router (Up...,471
8,VideoSecu,VideoSecu ML531BE TV Wall Mount for Most 27&qu...,448
9,"Arlo Technologies, Inc",Arlo - Wireless Home Security Camera System | ...,433
10,Samsung,Samsung 850 EVO 250GB 2.5-Inch SATA III Intern...,431